<template><div ref="rootRef" v-bind="$attrs" :class="classes"><div class="mg-cascader__control" role="combobox" :aria-expanded="open" tabindex="0" @click="toggle" @keydown.escape="close"><input v-if="filterable && open" ref="inputRef" class="mg-cascader__input" :value="query" :placeholder="placeholder" @input="query = ($event.target as HTMLInputElement).value" @click.stop><span v-else :class="displayLabel ? 'mg-cascader__value' : 'mg-cascader__placeholder'">{{ displayLabel || placeholder }}</span><button v-if="clearable && modelPath.length && !isDisabled" type="button" class="mg-cascader__clear" aria-label="清空" @click.stop="clear">×</button><span v-else>⌄</span></div><div v-show="open" class="mg-cascader__dropdown"><div v-if="query" class="mg-cascader__search"><button v-for="item in searchResults" :key="pathKey(item.path)" type="button" :disabled="item.node.disabled" @click="selectPath(item.path)">{{ item.labels.join(separator) }}</button><div v-if="!searchResults.length" class="mg-cascader__empty">暂无数据</div></div><div v-else class="mg-cascader__panels"><div v-for="(column, level) in columns" :key="level" class="mg-cascader__panel" role="menu"><button v-for="node in column" :key="String(nodeValue(node))" type="button" :class="['mg-cascader__option', { 'is-active': Object.is(activePath[level], nodeValue(node)) }]" :disabled="nodeDisabled(node)" @click="choose(node, level)"><slot name="default" :node="node" :data="node">{{ nodeLabel(node) }}</slot><span v-if="nodeChildren(node)?.length">›</span></button></div></div></div></div></template>
<script setup lang="ts">
import { computed, inject, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { formContextKey, formItemContextKey } from '@metagravity_cn/primitives'
type CascaderValue = string | number; export interface CascaderOption { value?: CascaderValue; label?: string; children?: CascaderOption[]; disabled?: boolean; [key: string]: unknown }
defineOptions({ name: 'MgCascader', inheritAttrs: false })
const props = withDefaults(defineProps<{ modelValue?: CascaderValue[]; options?: CascaderOption[]; props?: { value?: string; label?: string; children?: string; disabled?: string; checkStrictly?: boolean; emitPath?: boolean }; placeholder?: string; clearable?: boolean; filterable?: boolean; showAllLevels?: boolean; separator?: string; disabled?: boolean; validateEvent?: boolean }>(), { modelValue: () => [], options: () => [], placeholder: '请选择', clearable: true, showAllLevels: true, separator: ' / ', validateEvent: true })
const emit = defineEmits<{ 'update:modelValue': [value: CascaderValue[] | CascaderValue | undefined]; change: [value: CascaderValue[] | CascaderValue | undefined]; 'expand-change': [value: CascaderValue[]]; 'visible-change': [visible: boolean]; clear: [] }>()
const form = inject(formContextKey, undefined); const formItem = inject(formItemContextKey, undefined); const rootRef = ref<HTMLElement>(); const inputRef = ref<HTMLInputElement>(); const open = ref(false); const query = ref(''); const activePath = ref<CascaderValue[]>([...props.modelValue]); const isDisabled = computed(() => Boolean(props.disabled || form?.disabled?.value)); const modelPath = computed(() => Array.isArray(props.modelValue) ? props.modelValue : []); const valueField = computed(() => props.props?.value || 'value'); const labelField = computed(() => props.props?.label || 'label'); const childrenField = computed(() => props.props?.children || 'children'); const disabledField = computed(() => props.props?.disabled || 'disabled'); const nodeValue = (node: CascaderOption) => node[valueField.value] as CascaderValue; const nodeLabel = (node: CascaderOption) => String(node[labelField.value] ?? nodeValue(node)); const nodeChildren = (node: CascaderOption) => node[childrenField.value] as CascaderOption[] | undefined; const nodeDisabled = (node: CascaderOption) => Boolean(node[disabledField.value]); const pathKey = (path: CascaderValue[]) => path.join('/')
const columns = computed(() => { const result: CascaderOption[][] = [props.options]; let current = props.options; activePath.value.forEach((value) => { const node = current.find((item) => Object.is(nodeValue(item), value)); const children = node && nodeChildren(node); if (children?.length) { result.push(children); current = children } }); return result })
function resolvePath(path: CascaderValue[]) { const nodes: CascaderOption[] = []; let current = props.options; for (const value of path) { const node = current.find((item) => Object.is(nodeValue(item), value)); if (!node) break; nodes.push(node); current = nodeChildren(node) || [] } return nodes }
const displayLabel = computed(() => { const labels = resolvePath(modelPath.value).map(nodeLabel); return props.showAllLevels ? labels.join(props.separator) : labels.at(-1) || '' }); const classes = computed(() => ['mg-cascader', { 'is-open': open.value, 'is-disabled': isDisabled.value }])
const searchResults = computed(() => { const result: Array<{ node: CascaderOption; path: CascaderValue[]; labels: string[] }> = []; const walk = (nodes: CascaderOption[], path: CascaderValue[], labels: string[]) => nodes.forEach((node) => { const nextPath = [...path, nodeValue(node)], nextLabels = [...labels, nodeLabel(node)], children = nodeChildren(node); if (!children?.length || props.props?.checkStrictly) { if (nextLabels.join(' ').toLowerCase().includes(query.value.toLowerCase())) result.push({ node, path: nextPath, labels: nextLabels }) } if (children) walk(children, nextPath, nextLabels) }); walk(props.options, [], []); return result })
function update(value: CascaderValue[] | CascaderValue | undefined) { emit('update:modelValue', value); emit('change', value); if (props.validateEvent) void formItem?.validate('change') }
function choose(node: CascaderOption, level: number) { if (nodeDisabled(node)) return; activePath.value = [...activePath.value.slice(0, level), nodeValue(node)]; const children = nodeChildren(node); if (children?.length && !props.props?.checkStrictly) emit('expand-change', [...activePath.value]); else selectPath(activePath.value) }
function selectPath(path: CascaderValue[]) { activePath.value = [...path]; update(props.props?.emitPath === false ? path.at(-1) : [...path]); close() }
function clear() { activePath.value = []; update(props.props?.emitPath === false ? undefined : []); emit('clear') }
function toggle() { if (isDisabled.value) return; open.value ? close() : (open.value = true, emit('visible-change', true), setTimeout(() => inputRef.value?.focus())) } function close() { if (open.value) { open.value = false; query.value = ''; emit('visible-change', false) } }
function outside(event: Event) { if (!rootRef.value?.contains(event.target as Node)) close() } watch(() => props.modelValue, (value) => { if (Array.isArray(value)) activePath.value = [...value] })
onMounted(() => document.addEventListener('pointerdown', outside)); onBeforeUnmount(() => document.removeEventListener('pointerdown', outside)); defineExpose({ getCheckedNodes: () => resolvePath(modelPath.value), focus: () => rootRef.value?.querySelector<HTMLElement>('.mg-cascader__control')?.focus(), togglePopperVisible: toggle })
</script>
<style scoped>.mg-cascader { position: relative; display: inline-block; width: 100%; font-size: 14px; }.mg-cascader__control { box-sizing: border-box; display: flex; align-items: center; justify-content: space-between; min-height: 32px; padding: 1px 10px; cursor: pointer; background: #fff; border: 1px solid var(--mg-color-border, #dcdde1); border-radius: 3px; outline: 0; }.mg-cascader__control:focus,.mg-cascader.is-open .mg-cascader__control { border-color: var(--mg-color-primary, #0052d9); }.mg-cascader__placeholder { color: var(--mg-color-text-placeholder, #a1a7b3); }.mg-cascader__input { flex: 1; height: 28px; font: inherit; border: 0; outline: 0; }.mg-cascader__clear { margin-left: auto; cursor: pointer; background: none; border: 0; }.mg-cascader__dropdown { position: absolute; z-index: 2000; top: calc(100% + 6px); left: 0; min-width: 100%; background: #fff; border: 1px solid var(--mg-color-border, #dcdde1); border-radius: 4px; box-shadow: 0 6px 18px #0002; }.mg-cascader__panels { display: flex; }.mg-cascader__panel { min-width: 160px; max-height: 260px; padding: 6px 0; overflow: auto; border-right: 1px solid var(--mg-color-border-light, #ebecef); }.mg-cascader__panel:last-child { border: 0; }.mg-cascader__option,.mg-cascader__search button { display: flex; justify-content: space-between; width: 100%; padding: 8px 12px; font: inherit; text-align: left; cursor: pointer; background: none; border: 0; }.mg-cascader__option:hover,.mg-cascader__option.is-active,.mg-cascader__search button:hover { color: var(--mg-color-primary, #0052d9); background: var(--mg-color-fill-light, #f5f6f7); }.mg-cascader__search { min-width: 220px; max-height: 260px; padding: 6px 0; overflow: auto; }.mg-cascader__empty { padding: 18px; text-align: center; }.mg-cascader.is-disabled { opacity: .6; }</style>
