<template><div ref="rootRef" v-bind="$attrs" :class="classes"><div class="mg-tree-select__control" role="combobox" :aria-expanded="open" tabindex="0" @click="toggle" @keydown.escape="close"><div v-if="multiple && selectedNodes.length" class="mg-tree-select__tags"><span v-for="node in selectedNodes" :key="String(node.key)" class="mg-tree-select__tag">{{ node.label }}<button type="button" @click.stop="toggleNode(node)">×</button></span></div><input v-if="filterable && open" ref="inputRef" class="mg-tree-select__input" :value="query" :placeholder="placeholder" @input="query = ($event.target as HTMLInputElement).value" @click.stop><span v-else-if="!selectedNodes.length" class="mg-tree-select__placeholder">{{ placeholder }}</span><span v-else-if="!multiple">{{ selectedNodes[0]?.label }}</span><button v-if="clearable && selectedNodes.length" type="button" class="mg-tree-select__clear" aria-label="清空" @click.stop="clear">×</button><span v-else>⌄</span></div><div v-show="open" class="mg-tree-select__dropdown" role="tree"><div v-for="node in visibleNodes" :key="String(node.key)" class="mg-tree-select__row" role="treeitem" :aria-level="node.level + 1" :aria-expanded="node.children.length ? expanded.has(node.key) : undefined" :style="{ paddingLeft: `${10 + node.level * 18}px` }"><button v-if="node.children.length" type="button" class="mg-tree-select__expand" :aria-label="expanded.has(node.key) ? '收起' : '展开'" @click="toggleExpanded(node)">{{ expanded.has(node.key) ? '⌄' : '›' }}</button><span v-else class="mg-tree-select__spacer" /><input v-if="showCheckbox || multiple" type="checkbox" :checked="isSelected(node.key)" :disabled="node.disabled" @change="toggleNode(node)"><button type="button" class="mg-tree-select__label" :disabled="node.disabled" @click="toggleNode(node)"><slot :data="node.raw" :node="node">{{ node.label }}</slot></button></div><div v-if="!visibleNodes.length" class="mg-tree-select__empty">暂无数据</div></div></div></template>
<script setup lang="ts">
import { computed, inject, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { formContextKey, formItemContextKey } from '@mg-design/primitives'
export type TreeKey = string | number | boolean; export interface TreeSelectNode { id?: TreeKey; label?: string; children?: TreeSelectNode[]; disabled?: boolean; [key: string]: unknown }; export interface FlatTreeSelectNode { key: TreeKey; label: string; children: TreeSelectNode[]; disabled: boolean; level: number; parent?: TreeKey; raw: TreeSelectNode }
defineOptions({ name: 'MgTreeSelect', inheritAttrs: false })
const props = withDefaults(defineProps<{ modelValue?: TreeKey | TreeKey[]; data?: TreeSelectNode[]; nodeKey?: string; props?: { value?: string; label?: string; children?: string; disabled?: string }; multiple?: boolean; showCheckbox?: boolean; checkStrictly?: boolean; filterable?: boolean; clearable?: boolean; placeholder?: string; defaultExpandAll?: boolean; disabled?: boolean; validateEvent?: boolean }>(), { modelValue: undefined, data: () => [], nodeKey: 'id', placeholder: '请选择', clearable: true, validateEvent: true })
const emit = defineEmits<{ 'update:modelValue': [value: TreeKey | TreeKey[] | undefined]; change: [value: TreeKey | TreeKey[] | undefined]; 'visible-change': [visible: boolean]; clear: []; 'node-click': [data: TreeSelectNode] }>()
const form = inject(formContextKey, undefined); const formItem = inject(formItemContextKey, undefined); const rootRef = ref<HTMLElement>(); const inputRef = ref<HTMLInputElement>(); const open = ref(false); const query = ref(''); const expanded = ref(new Set<TreeKey>()); const valueField = computed(() => props.props?.value || props.nodeKey); const labelField = computed(() => props.props?.label || 'label'); const childrenField = computed(() => props.props?.children || 'children'); const disabledField = computed(() => props.props?.disabled || 'disabled'); const isDisabled = computed(() => Boolean(props.disabled || form?.disabled?.value)); const flatNodes = computed(() => { const result: FlatTreeSelectNode[] = []; const walk = (nodes: TreeSelectNode[], level = 0, parent?: TreeKey) => nodes.forEach((raw) => { const key = raw[valueField.value] as TreeKey; const children = (raw[childrenField.value] as TreeSelectNode[]) || []; result.push({ key, label: String(raw[labelField.value] ?? key), children, disabled: Boolean(raw[disabledField.value]), level, parent, raw }); walk(children, level + 1, key) }); walk(props.data); return result })
const modelValues = computed(() => props.multiple ? (Array.isArray(props.modelValue) ? props.modelValue : []) : props.modelValue === undefined ? [] : [props.modelValue as TreeKey]); const isSelected = (key: TreeKey) => modelValues.value.some((value) => Object.is(value, key)); const selectedNodes = computed(() => modelValues.value.map((key) => flatNodes.value.find((node) => Object.is(node.key, key))).filter((node): node is FlatTreeSelectNode => Boolean(node))); const visibleNodes = computed(() => flatNodes.value.filter((node) => { if (query.value) return node.label.toLowerCase().includes(query.value.toLowerCase()); let parent = node.parent; while (parent !== undefined) { if (!expanded.value.has(parent)) return false; parent = flatNodes.value.find((item) => Object.is(item.key, parent))?.parent } return true })); const classes = computed(() => ['mg-tree-select', { 'is-open': open.value, 'is-disabled': isDisabled.value }])
function update(value: TreeKey | TreeKey[] | undefined) { emit('update:modelValue', value); emit('change', value); if (props.validateEvent) void formItem?.validate('change') }
function toggleNode(node: FlatTreeSelectNode) { if (node.disabled || isDisabled.value) return; emit('node-click', node.raw); if (props.multiple) { const values = [...modelValues.value]; const index = values.findIndex((value) => Object.is(value, node.key)); index >= 0 ? values.splice(index, 1) : values.push(node.key); update(values) } else { update(node.key); close() } }
function toggleExpanded(node: FlatTreeSelectNode) { const next = new Set(expanded.value); next.has(node.key) ? next.delete(node.key) : next.add(node.key); expanded.value = next }
function clear() { update(props.multiple ? [] : undefined); emit('clear') } function toggle() { if (isDisabled.value) return; open.value ? close() : (open.value = true, emit('visible-change', true), setTimeout(() => inputRef.value?.focus())) } function close() { if (open.value) { open.value = false; query.value = ''; emit('visible-change', false) } } function outside(event: Event) { if (!rootRef.value?.contains(event.target as Node)) close() }
watch(() => props.data, () => { if (props.defaultExpandAll) expanded.value = new Set(flatNodes.value.filter((node) => node.children.length).map((node) => node.key)) }, { immediate: true })
onMounted(() => document.addEventListener('pointerdown', outside)); onBeforeUnmount(() => document.removeEventListener('pointerdown', outside)); defineExpose({ getCheckedKeys: () => [...modelValues.value], setCheckedKeys: (keys: TreeKey[]) => update(keys), getCurrentKey: () => modelValues.value[0], focus: () => rootRef.value?.querySelector<HTMLElement>('.mg-tree-select__control')?.focus() })
</script>
<style scoped>.mg-tree-select { position: relative; display: inline-block; width: 100%; font-size: 14px; }.mg-tree-select__control { box-sizing: border-box; display: flex; align-items: center; gap: 6px; min-height: 32px; padding: 1px 10px; cursor: pointer; background: #fff; border: 1px solid var(--mg-color-border, #dcdde1); border-radius: 3px; outline: 0; }.mg-tree-select__control:focus,.mg-tree-select.is-open .mg-tree-select__control { border-color: var(--mg-color-primary, #0052d9); }.mg-tree-select__placeholder { flex: 1; color: var(--mg-color-text-placeholder, #a1a7b3); }.mg-tree-select__input { flex: 1; min-width: 0; height: 28px; font: inherit; border: 0; outline: 0; }.mg-tree-select__tags { display: flex; flex: 1; flex-wrap: wrap; gap: 4px; }.mg-tree-select__tag { display: inline-flex; gap: 4px; padding: 1px 6px; background: var(--mg-color-fill-light, #f5f6f7); border-radius: 2px; }.mg-tree-select__tag button,.mg-tree-select__clear { padding: 0; cursor: pointer; background: none; border: 0; }.mg-tree-select__clear { margin-left: auto; }.mg-tree-select__dropdown { position: absolute; z-index: 2000; top: calc(100% + 6px); left: 0; box-sizing: border-box; width: 100%; max-height: 280px; padding: 6px 0; overflow: auto; background: #fff; border: 1px solid var(--mg-color-border, #dcdde1); border-radius: 4px; box-shadow: 0 6px 18px #0002; }.mg-tree-select__row { display: flex; align-items: center; min-height: 34px; padding-right: 8px; }.mg-tree-select__row:hover { background: var(--mg-color-fill-light, #f5f6f7); }.mg-tree-select__expand,.mg-tree-select__label { padding: 4px; cursor: pointer; background: none; border: 0; }.mg-tree-select__spacer { width: 22px; }.mg-tree-select__label { flex: 1; overflow: hidden; font: inherit; text-align: left; text-overflow: ellipsis; white-space: nowrap; }.mg-tree-select__empty { padding: 18px; text-align: center; }.mg-tree-select.is-disabled { opacity: .6; }</style>
