<template>
  <div ref="rootRef" v-bind="$attrs" :class="classes" @keydown="handleKeydown">
    <div class="mg-autocomplete__control"><span v-if="$slots.prefix" class="mg-autocomplete__prefix"><slot name="prefix" /></span><input ref="inputRef" class="mg-autocomplete__input" :value="modelValue" :placeholder="placeholder" :disabled="isDisabled" :name="name" :aria-expanded="open" role="combobox" :aria-controls="listId" :aria-activedescendant="activeId" autocomplete="off" @input="handleInput" @focus="handleFocus" @blur="emit('blur', $event)"><button v-if="clearable && modelValue" type="button" class="mg-autocomplete__clear" aria-label="清空" @mousedown.prevent @click="clear">×</button><span v-if="$slots.suffix" class="mg-autocomplete__suffix"><slot name="suffix" /></span></div>
    <div v-show="open" :id="listId" class="mg-autocomplete__dropdown" role="listbox"><div v-if="loading" class="mg-autocomplete__empty">加载中…</div><button v-for="(item, index) in suggestions" v-else :id="`${listId}-${index}`" :key="index" type="button" :class="['mg-autocomplete__item', { 'is-active': index === activeIndex }]" role="option" @mousedown.prevent="select(item)"><slot :item="item">{{ labelOf(item) }}</slot></button><div v-if="!loading && !suggestions.length" class="mg-autocomplete__empty">暂无数据</div></div>
  </div>
</template>
<script setup lang="ts">
import { computed, inject, onBeforeUnmount, onMounted, ref } from 'vue'
import { formContextKey, formItemContextKey, useStableId } from '@metagravity_cn/primitives'
export type AutocompleteItem = Record<string, unknown>
defineOptions({ name: 'MgAutocomplete', inheritAttrs: false })
const props = withDefaults(defineProps<{ modelValue?: string; fetchSuggestions?: (query: string, callback: (items: AutocompleteItem[]) => void) => void | AutocompleteItem[] | Promise<AutocompleteItem[]>; placeholder?: string; disabled?: boolean; clearable?: boolean; triggerOnFocus?: boolean; debounce?: number; valueKey?: string; name?: string; selectWhenUnmatched?: boolean; hideLoading?: boolean; validateEvent?: boolean }>(), { modelValue: '', triggerOnFocus: true, debounce: 300, valueKey: 'value', validateEvent: true })
const emit = defineEmits<{ 'update:modelValue': [value: string]; input: [value: string]; change: [value: string]; select: [item: AutocompleteItem]; focus: [event: FocusEvent]; blur: [event: FocusEvent]; clear: [] }>()
const form = inject(formContextKey, undefined); const formItem = inject(formItemContextKey, undefined); const rootRef = ref<HTMLElement>(); const inputRef = ref<HTMLInputElement>(); const suggestions = ref<AutocompleteItem[]>([]); const open = ref(false); const loading = ref(false); const activeIndex = ref(-1); const listId = useStableId('mg-autocomplete-list'); let timer: ReturnType<typeof setTimeout> | undefined; let request = 0
const isDisabled = computed(() => Boolean(props.disabled || form?.disabled?.value)); const classes = computed(() => ['mg-autocomplete', { 'is-open': open.value, 'is-disabled': isDisabled.value }]); const activeId = computed(() => activeIndex.value >= 0 ? `${listId}-${activeIndex.value}` : undefined); const labelOf = (item: AutocompleteItem) => String(item[props.valueKey] ?? '')
async function fetch(query: string) { if (!props.fetchSuggestions) return; const token = ++request; loading.value = !props.hideLoading; const done = (items: AutocompleteItem[]) => { if (token !== request) return; suggestions.value = items || []; loading.value = false; open.value = true; activeIndex.value = suggestions.value.length ? 0 : -1 }; try { const result = props.fetchSuggestions(query, done); if (Array.isArray(result)) done(result); else if (result instanceof Promise) done(await result) } catch { done([]) } }
function schedule(query: string) { clearTimeout(timer); timer = setTimeout(() => void fetch(query), props.debounce) }
function handleInput(event: Event) { const value = (event.target as HTMLInputElement).value; emit('update:modelValue', value); emit('input', value); emit('change', value); schedule(value) }
function handleFocus(event: FocusEvent) { emit('focus', event); if (props.triggerOnFocus) schedule(props.modelValue) }
function select(item: AutocompleteItem) { const value = labelOf(item); emit('update:modelValue', value); emit('select', item); emit('change', value); open.value = false; if (props.validateEvent) void formItem?.validate('change') }
function clear() { emit('update:modelValue', ''); emit('clear'); emit('change', ''); suggestions.value = []; open.value = false }
function handleKeydown(event: KeyboardEvent) { if (event.key === 'ArrowDown' || event.key === 'ArrowUp') { event.preventDefault(); open.value = true; const d = event.key === 'ArrowDown' ? 1 : -1; activeIndex.value = (activeIndex.value + d + suggestions.value.length) % Math.max(1, suggestions.value.length) } else if (event.key === 'Enter') { const item = suggestions.value[activeIndex.value]; if (open.value && item) { event.preventDefault(); select(item) } else if (props.selectWhenUnmatched) emit('select', { [props.valueKey]: props.modelValue }) } else if (event.key === 'Escape') open.value = false }
function outside(event: Event) { if (!rootRef.value?.contains(event.target as Node)) open.value = false }
onMounted(() => document.addEventListener('pointerdown', outside)); onBeforeUnmount(() => { document.removeEventListener('pointerdown', outside); clearTimeout(timer) })
defineExpose({ focus: () => inputRef.value?.focus(), blur: () => inputRef.value?.blur(), close: () => { open.value = false } })
</script>
<style scoped>.mg-autocomplete { position: relative; display: inline-block; width: 100%; }.mg-autocomplete__control { box-sizing: border-box; display: flex; align-items: center; min-height: 32px; padding: 1px 10px; background: #fff; border: 1px solid var(--mg-color-border, #dcdde1); border-radius: 3px; }.mg-autocomplete__control:focus-within { border-color: var(--mg-color-primary, #0052d9); box-shadow: 0 0 0 1px var(--mg-color-primary, #0052d9) inset; }.mg-autocomplete__input { flex: 1; min-width: 0; height: 28px; padding: 0; font: inherit; border: 0; outline: 0; }.mg-autocomplete__prefix,.mg-autocomplete__suffix { display: inline-flex; margin-right: 7px; }.mg-autocomplete__suffix { margin: 0 0 0 7px; }.mg-autocomplete__clear { cursor: pointer; background: none; border: 0; }.mg-autocomplete__dropdown { position: absolute; z-index: 2000; top: calc(100% + 6px); left: 0; box-sizing: border-box; width: 100%; max-height: 260px; padding: 6px 0; overflow: auto; background: #fff; border: 1px solid var(--mg-color-border, #dcdde1); border-radius: 4px; box-shadow: 0 6px 18px #0002; }.mg-autocomplete__item { display: block; width: 100%; min-height: 34px; padding: 7px 12px; overflow: hidden; font: inherit; text-align: left; text-overflow: ellipsis; white-space: nowrap; cursor: pointer; background: none; border: 0; }.mg-autocomplete__item:hover,.mg-autocomplete__item.is-active { background: var(--mg-color-fill-light, #f5f6f7); }.mg-autocomplete__empty { padding: 16px; color: var(--mg-color-text-secondary, #6f7686); text-align: center; }.mg-autocomplete.is-disabled { opacity: .6; }</style>
