<template>
  <div ref="rootRef" v-bind="$attrs" :class="classes" @keydown="handleKeydown">
    <div class="mg-select__control" role="combobox" :aria-expanded="open" :aria-controls="listboxId" :aria-activedescendant="highlightedId" :tabindex="filterable ? -1 : 0" @click="toggle">
      <div v-if="multiple && selectedOptions.length" class="mg-select__tags"><span v-for="option in collapsedOptions" :key="option.id" class="mg-select__tag">{{ option.label }}<button v-if="!isDisabled" type="button" aria-label="移除" @click.stop="remove(option)">×</button></span><span v-if="collapseTags && selectedOptions.length > maxCollapseTags" class="mg-select__tag">+ {{ selectedOptions.length - maxCollapseTags }}</span></div>
      <span v-else-if="!filterable && selectedOptions[0]" class="mg-select__value"><slot name="label" :label="selectedOptions[0].label" :value="selectedOptions[0].value">{{ selectedOptions[0].label }}</slot></span>
      <input v-if="filterable" ref="inputRef" class="mg-select__input" :value="query" :placeholder="selectedOptions.length ? '' : placeholder" :disabled="isDisabled" :readonly="!filterable" @input="onQuery" @focus="openMenu" @click.stop>
      <span v-else-if="!selectedOptions.length" class="mg-select__placeholder">{{ placeholder }}</span>
      <button v-if="clearable && selectedOptions.length && !isDisabled" type="button" class="mg-select__clear" aria-label="清空" @click.stop="clear">×</button><span v-else class="mg-select__arrow" aria-hidden="true">⌄</span>
    </div>
    <div v-show="open" :id="listboxId" class="mg-select__dropdown" role="listbox" :aria-multiselectable="multiple || undefined"><slot /><div v-if="!visibleOptions.length" class="mg-select__empty"><slot name="empty">{{ noDataText }}</slot></div></div>
  </div>
</template>
<script setup lang="ts">
import { computed, inject, onBeforeUnmount, onMounted, provide, ref } from 'vue'
import { formContextKey, formItemContextKey, useStableId } from '@metagravity_cn/primitives'
import { selectContextKey, type SelectOptionRecord } from '../select-context'
import type { SelectionValue } from '../selection-context'
defineOptions({ name: 'MgSelect', inheritAttrs: false })
const props = withDefaults(defineProps<{ modelValue?: SelectionValue | SelectionValue[]; multiple?: boolean; disabled?: boolean; clearable?: boolean; filterable?: boolean; allowCreate?: boolean; placeholder?: string; size?: 'large' | 'default' | 'small'; multipleLimit?: number; collapseTags?: boolean; maxCollapseTags?: number; noDataText?: string; reserveKeyword?: boolean; validateEvent?: boolean }>(), { modelValue: undefined, placeholder: '请选择', maxCollapseTags: 1, noDataText: '暂无数据', validateEvent: true })
const emit = defineEmits<{ 'update:modelValue': [value: SelectionValue | SelectionValue[] | undefined]; change: [value: SelectionValue | SelectionValue[] | undefined]; 'visible-change': [visible: boolean]; clear: []; removeTag: [value: SelectionValue] }>()
const form = inject(formContextKey, undefined); const formItem = inject(formItemContextKey, undefined); const rootRef = ref<HTMLElement>(); const inputRef = ref<HTMLInputElement>(); const open = ref(false); const query = ref(''); const options = ref<SelectOptionRecord[]>([]); const highlightedIndex = ref(-1); const listboxId = useStableId('mg-select-list')
const isDisabled = computed(() => Boolean(props.disabled || form?.disabled?.value)); const modelArray = computed(() => props.multiple ? (Array.isArray(props.modelValue) ? props.modelValue : []) : props.modelValue === undefined || props.modelValue === null || props.modelValue === '' ? [] : [props.modelValue]); const selected = (value: SelectionValue) => modelArray.value.some((item) => Object.is(item, value)); const selectedOptions = computed(() => modelArray.value.map((value) => options.value.find((option) => Object.is(option.value, value)) || { value, label: String(value), disabled: false, id: String(value) })); const collapsedOptions = computed(() => props.collapseTags ? selectedOptions.value.slice(0, props.maxCollapseTags) : selectedOptions.value); const visible = (option: SelectOptionRecord) => !query.value || option.label.toLocaleLowerCase().includes(query.value.toLocaleLowerCase()); const visibleOptions = computed(() => options.value.filter(visible)); const highlightedId = computed(() => visibleOptions.value[highlightedIndex.value]?.id); const classes = computed(() => ['mg-select', props.size && `mg-select--${props.size}`, { 'is-open': open.value, 'is-disabled': isDisabled.value, 'is-multiple': props.multiple }])
function register(option: SelectOptionRecord) { if (!options.value.some((item) => item.id === option.id)) options.value.push(option) }
function unregister(id: string) { options.value = options.value.filter((item) => item.id !== id) }
function update(value: SelectionValue | SelectionValue[] | undefined) { emit('update:modelValue', value); emit('change', value); if (props.validateEvent) void formItem?.validate('change') }
function selectOption(option: SelectOptionRecord) { if (option.disabled) return; if (props.multiple) { const values = [...modelArray.value]; const index = values.findIndex((value) => Object.is(value, option.value)); if (index >= 0) values.splice(index, 1); else if (!props.multipleLimit || values.length < props.multipleLimit) values.push(option.value); update(values); if (!props.reserveKeyword) query.value = '' } else { update(option.value); closeMenu() } }
function remove(option: SelectOptionRecord) { if (!props.multiple) return; update(modelArray.value.filter((value) => !Object.is(value, option.value))); emit('removeTag', option.value) }
function clear() { update(props.multiple ? [] : undefined); query.value = ''; emit('clear') }
function openMenu() { if (isDisabled.value || open.value) return; open.value = true; highlightedIndex.value = Math.max(0, visibleOptions.value.findIndex((option) => selected(option.value))); emit('visible-change', true) }
function closeMenu() { if (!open.value) return; open.value = false; highlightedIndex.value = -1; emit('visible-change', false) }
function toggle() { open.value ? closeMenu() : openMenu(); if (props.filterable) inputRef.value?.focus() }
function onQuery(event: Event) { query.value = (event.target as HTMLInputElement).value; openMenu(); highlightedIndex.value = 0 }
function handleKeydown(event: KeyboardEvent) { if (['ArrowDown','ArrowUp'].includes(event.key)) { event.preventDefault(); openMenu(); const direction = event.key === 'ArrowDown' ? 1 : -1; highlightedIndex.value = (highlightedIndex.value + direction + visibleOptions.value.length) % Math.max(1, visibleOptions.value.length) } else if (event.key === 'Enter' && open.value) { event.preventDefault(); const option = visibleOptions.value[highlightedIndex.value]; if (option) selectOption(option) } else if (event.key === 'Escape') closeMenu() }
function onDocumentPointer(event: Event) { if (!rootRef.value?.contains(event.target as Node)) closeMenu() }
function focus() { (inputRef.value || rootRef.value?.querySelector<HTMLElement>('.mg-select__control'))?.focus() } function blur() { inputRef.value?.blur(); closeMenu() }
provide(selectContextKey, { selected, select: selectOption, register, unregister, visible, highlightedId })
onMounted(() => document.addEventListener('pointerdown', onDocumentPointer)); onBeforeUnmount(() => document.removeEventListener('pointerdown', onDocumentPointer))
defineExpose({ focus, blur, selectedLabel: computed(() => selectedOptions.value[0]?.label), open: openMenu, close: closeMenu })
</script>
<style scoped>.mg-select { position: relative; box-sizing: border-box; display: inline-block; width: 100%; font-size: 14px; }.mg-select__control { box-sizing: border-box; display: flex; align-items: center; gap: 6px; min-height: 32px; padding: 1px 10px; cursor: pointer; background: #fff; border: 1px solid var(--mg-color-border, #dcdde1); border-radius: 3px; outline: none; }.mg-select__control:hover,.mg-select__control:focus-visible,.mg-select.is-open .mg-select__control { border-color: var(--mg-color-primary, #0052d9); }.mg-select__placeholder { flex: 1; color: var(--mg-color-text-placeholder, #a1a7b3); }.mg-select__value,.mg-select__input { flex: 1; min-width: 0; }.mg-select__input { height: 26px; padding: 0; font: inherit; border: 0; outline: 0; }.mg-select__arrow { margin-left: auto; transition: transform .2s; }.mg-select.is-open .mg-select__arrow { transform: rotate(180deg); }.mg-select__clear { margin-left: auto; cursor: pointer; background: none; border: 0; }.mg-select__tags { display: flex; flex: 1; flex-wrap: wrap; gap: 4px; }.mg-select__tag { display: inline-flex; gap: 4px; align-items: center; padding: 1px 6px; background: var(--mg-color-fill-light, #f5f6f7); border-radius: 2px; }.mg-select__tag button { padding: 0; background: none; border: 0; cursor: pointer; }.mg-select__dropdown { position: absolute; z-index: 2000; top: calc(100% + 6px); left: 0; box-sizing: border-box; width: 100%; max-height: 260px; padding: 6px 0; overflow: auto; background: #fff; border: 1px solid var(--mg-color-border, #dcdde1); border-radius: 4px; box-shadow: 0 6px 18px #0002; }.mg-select__empty { padding: 18px; color: var(--mg-color-text-secondary, #6f7686); text-align: center; }.mg-select.is-disabled { cursor: not-allowed; opacity: .6; }.mg-select--large .mg-select__control { min-height: 40px; }.mg-select--small .mg-select__control { min-height: 24px; font-size: 12px; }</style>
